#!/usr/bin/env perl

use warnings;
use strict;

if ($#ARGV != 2){
    printf STDERR "Usage: synner start <client> <server>\n";
    exit(1);
}
my $op = $ARGV[0];
my ($cu, $ch) = split /\@/, $ARGV[1];
if ($ch) {
    $cu = "$cu@";
}else{
    $ch = $cu;
    $cu = '';
}
my ($su, $sh) = split /\@/, $ARGV[2];
if ($sh) {
    $su = "$su@";
}else{
    $sh = $su;
    $su = '';
}
if ($op eq 'stop'){
    print "fab -H $su\$(vms $sh) server:stop; ".
          "fab -H $cu\$(vms $ch) client:stop\n";
}else{
    print "fab -H $su\$(vms $sh) server:./$sh.conf".
          "fab -H $cu\$(vms $ch) client:\$(vms $sh),$ch\n";
}
